# Generated by Django 3.0.7 on 2020-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foomodel',
            name='foo_field',
            field=models.TextField(default='foo_update'),
        ),
    ]
